name: First Workflow
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "Hello World"
          current_date=$(date +"%Y-%m-%d")
          echo "Current date: $current_date"
          cur_path=$(pwd)
          echo "Current path: $cur_path"
      - name: Print Goodbye
        run: echo "Done - bye"
        
